//=========================================================================
//
//  This skeleton was generated by Mouse 1.7 at 2015-09-07 22:02:33 GMT
//  from grammar
//    '/home/bpdp/kerjaan/git-repos/vastix/jifa/src/test/grammar/JifaGramma
//    r.peg'.
//
//=========================================================================

import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
import java.io.IOException;

import mouse.runtime.*;

class JifaSemantics extends mouse.runtime.SemanticsBase
{

    OkHttpClient client = new OkHttpClient();

    String run(String url) throws IOException {

        Request request = new Request.Builder()
            .url(url)
            .build();

        Response response = client.newCall(request).execute();
        return response.body().string();
    }


  //-------------------------------------------------------------------
  //  Line = Force Space+ Propositional+
  //-------------------------------------------------------------------
  //void lineProcessed() throws IOException 
  void lineProcessed()
    {
         //String response = run((String)rhs(2).get());
         //System.out.println(response);
         System.out.println("Kiri = " + (String)lhs().get());
         for (int i=0; i<rhsSize(); i+=1) {
             System.out.println("Isi = " + (String)rhs(i).get());
         }
    }
  
}
