//=========================================================================
//
//  This skeleton was generated by Mouse 1.7 at 2015-09-07 12:49:34 GMT
//  from grammar
//    '/home/bpdp/kerjaan/git-repos/vastix/jifa/src/test/grammar/JifaGramma
//    r.peg'.
//
//=========================================================================

class JifaSemantics extends mouse.runtime.SemanticsBase
{
}
