//=========================================================================
//
//  This skeleton was generated by Mouse 1.7 at 2015-09-09 04:51:40 GMT
//  from grammar
//    '/home/bpdp/kerjaan/git-repos/vastix/jifa/src/test/grammar/JifaGramma
//    r.peg'.
//
//=========================================================================
package name.bpdp.vastix.jifa;

class JifaSemantics extends mouse.runtime.SemanticsBase
{
  //-------------------------------------------------------------------
  //  Line = Force Space Propositional+
  //-------------------------------------------------------------------
  void lineProcessed()
    {}
  
  //-------------------------------------------------------------------
  //  Propositional = (Space / Lcase / Ucase / Digits / Symbols)+
  //-------------------------------------------------------------------
  void getPropositional()
    {}
  
}
